data_dir: ./tdata
yadisk:
- https://disk.yandex.ru/d/4o0wqiQaJ45Jyw
- https://disk.yandex.ru/d/VRMe3QHC_zCJpA
- https://disk.yandex.ru/d/Hbcp2fYTWLpdpg
- https://disk.yandex.ru/d/BxK8eHliLpo-Rw
- https://disk.yandex.ru/d/ndi89RTeOmxhwA

